yaml
# Branch Protection Rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "CodeQL Analysis"
          - "Dependency Review"
          - "Secret Scanning"
          - "Vulnerability Scan"
          - "Security Audit"
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 2
      enforce_admins: true
      restrictions:
        users: []
        teams: ["trusted-contributors"]
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      required_signatures: true

  - name: dev
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "CodeQL Analysis"
          - "Dependency Review"
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1
      enforce_admins: false
      restrictions:
        users: []
        teams: ["developers"]
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true

  - name: release/*
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "CodeQL Analysis"
          - "Dependency Review"
          - "Secret Scanning"
          - "Vulnerability Scan"
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 2
      enforce_admins: true
      restrictions:
        users: []
        teams: ["release-managers"]
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
 